# Generated by Django 5.2.3 on 2025-06-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="event title", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("holiday", "Holiday"),
                            ("reminder", "Reminder"),
                        ],
                        help_text="category of event",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="date whene the event is place",
                        verbose_name="Event Date",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="time when the event is start",
                        verbose_name="Start Time",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="time when the event is start",
                        verbose_name="Start Time",
                    ),
                ),
                (
                    "is_virtual",
                    models.BooleanField(
                        default=False,
                        help_text="is event is virtual or not",
                        verbose_name="Is Virtual",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="description of the event",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
